import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/toaster";
<<<<<<< HEAD
import ReactQueryProvider from "@/store/TanstackQuery";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
=======
import TanstackQueryProviders from "@/store/TanstackQuery";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

>>>>>>> 377a930d016293d9f1a30683c3fc7fe22d214c62

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <ReactQueryProvider>
        <Provider>{children}</Provider>
        <ReactQueryDevtools />
        </ReactQueryProvider>
=======
        <TanstackQueryProviders><Provider>{children}
          <ReactQueryDevtools initialIsOpen={false} /></Provider></TanstackQueryProviders>



>>>>>>> 377a930d016293d9f1a30683c3fc7fe22d214c62
        <Toaster />
      </body>
    </html>
  );
}
